services:

  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dscatalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: local_backend
    environment:
      APP_PROFILE: dev
      DB_URL: jdbc:postgresql://postgres:5432/dscatalog
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      CLIENT_ID: dscatalog
      CLIENT_SECRET: dscatalog123
      JWT_SECRET: MY-JWT-SECRET
      JWT_DURATION: 86400
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
