name: CI - Build, Test and Publish Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dscatalog-bds3-backend3-main

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build e Testes
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Login no GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/poc-catalogo:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/poc-catalogo:latest


